modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
[[mods]] #mandatory
modId="betterbundles" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Bundles" #mandatory
logoFile="logo.png" #optional
authors="Cheaterpaul" #optional
description='''
Mod that makes bundles colorizable and copper, iron, silver, gold, diamond and netherite bundles
'''
[[dependencies.betterbundles]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.betterbundles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
